#include "../include/types.h"
#include "../include/config.h"
#include "../include/pokemon.h"
#include "../include/constants/species.h"

const u16 UNUSED BaseExperienceTable[] =
{
    [SPECIES_NONE                       ] = 0,
    [SPECIES_KAMMON                     ] = 40,
    [SPECIES_PUNIMON                    ] = 40,
    [SPECIES_POGLMON                    ] = 40,
    [SPECIES_PICHIMON                   ] = 40,
    [SPECIES_PURURUMON                  ] = 40,
    [SPECIES_POYOMON                    ] = 40,
    [SPECIES_POLPOLMON                  ] = 40,
    [SPECIES_KURAMON                    ] = 40,
    [SPECIES_KOROMON                    ] = 50,
    [SPECIES_KOMAMON                    ] = 50,
    [SPECIES_PULMON                     ] = 50,
    [SPECIES_YAONGMON                   ] = 50,
    [SPECIES_MOTIMON                    ] = 50,
    [SPECIES_SEEDMON                    ] = 50,
    [SPECIES_DUNGSILMON                 ] = 50,
    [SPECIES_UPAMON                     ] = 50,
    [SPECIES_POROMON                    ] = 50,
    [SPECIES_ONIMON                     ] = 50,
    [SPECIES_TOKOMON                    ] = 50,
    [SPECIES_CUPIMON                    ] = 50,
    [SPECIES_CAPRIMON                   ] = 50,
    [SPECIES_PICKMON                    ] = 50,
    [SPECIES_TSUMEMON                   ] = 50,
    [SPECIES_PAGUMON                    ] = 50,
    [SPECIES_AGUMON                     ] = 50,
    [SPECIES_PAPIMON                    ] = 50,
    [SPECIES_TENTAMON                   ] = 50,
    [SPECIES_PIYOMON                    ] = 50,
    [SPECIES_PALMON                     ] = 50,
    [SPECIES_SHIRAMON                   ] = 50,
    [SPECIES_PADAKMON                   ] = 50,
    [SPECIES_PLOTMON                    ] = 50,
    [SPECIES_V-MON                      ] = 50,
    [SPECIES_HAWKMON                    ] = 50,
    [SPECIES_ARMAMON                    ] = 50,
    [SPECIES_CHUCHUMON                  ] = 50,
    [SPECIES_BETAMON                    ] = 50,
    [SPECIES_CHUMON                     ] = 50,
    [SPECIES_PICODEVILMON               ] = 50,
    [SPECIES_KERAMON                    ] = 50,
    [SPECIES_GUILMON                    ] = 50,
    [SPECIES_RENAMON                    ] = 50,
    [SPECIES_TERRIERMON                 ] = 50,
    [SPECIES_LOPMON                     ] = 50,
    [SPECIES_ELECMON                    ] = 50,
    [SPECIES_IMPMON                     ] = 50,
    [SPECIES_ULTUNGMON                  ] = 50,
    [SPECIES_TOPNIMON                   ] = 50,
    [SPECIES_GAZIMON                    ] = 50,
    [SPECIES_LUCEMON                    ] = 50,
    [SPECIES_BURGERMON                  ] = 50,
    [SPECIES_BLUCOMON                   ] = 50,
    [SPECIES_COMANDRAMON                ] = 50,
    [SPECIES_SHOUTMON                   ] = 50,
    [SPECIES_STARMONS                   ] = 50,
    [SPECIES_SPARROWMON                 ] = 50,
    [SPECIES_IGOSMON                    ] = 50,
    [SPECIES_ELIZAMON                   ] = 50,
    [SPECIES_UKKOMON                    ] = 50,
};
